### ISSUE TITLE
The website project looks so cool, may I fork and build a new personal blog based on it?

### ISSUE THREAD

**Issue by FeynmanZhou** [avatar-kaleb/kalebmckelvey-site#18]
Hey, I found your blog website from gatsbyjs website,  it's beautiful, and looks so cool. May I fork it and build a new personal blog based on it?

Thanks.

**Comment by FeynmanZhou** [comment]
@avatar-kaleb  One more question, I have cloned this repo but I can't build successfully in my MacOS, also build failed in Netlify, could you tell us how to build and preview locally?

**Comment by avatar-kaleb** [comment]
Thank you so much Feynman! You are absolutely welcome to fork it and change the text / colors / data etc to your liking.

Could you post the error you are getting on your MacOS?

I will note one thing: This is using material design from the React-MD library, but in the future I will be updating to Material UI as its better supported.

**Comment by FeynmanZhou** [comment]
@avatar-kaleb  See the error that I got on my MacOS, thanks for your help

```
$ npm run develop

ERROR in ./src/components/ToolbarActions/ToolbarActions.scss (./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/lib??postcss-3!./node_modules/sass-loader/lib/loader.js??ref--12-oneOf-1-3!./src/components/ToolbarActions/ToolbarActions.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir '/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:786:3)
    at Object.getInstalledBinaries (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/node-sass/lib/extensions.js:130:13)
    at foundBinariesList (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/Users/zhoupengfei/GitFolder/kalebmckelvey-site/node_modules/sass-loader/lib/loader.js:46:72)
 @ ./src/components/ToolbarActions/ToolbarActions.scss 2:14-237 21:1-42:3 22:19-242
 @ ./src/components/ToolbarActions/ToolbarActions.jsx
 @ ./src/components/Navigation/Navigation.jsx
 @ ./src/layouts/index.jsx
 @ ./node_modules/gatsby-plugin-layout/wrap-page.js
 @ ./node_modules/gatsby-plugin-layout/gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```

**Comment by FeynmanZhou** [comment]
Now I can successfully compiled, but it returns like following:

![image](https://user-images.githubusercontent.com/40452856/69433020-c5421b00-0d75-11ea-9a4e-56e60441e9a9.png)

Then it always stuck in this page. how to preview this site correctly?

![image](https://user-images.githubusercontent.com/40452856/69433058-d723be00-0d75-11ea-85da-532e2becf831.png)

**Comment by FeynmanZhou** [comment]
@avatar-kaleb I forked this repo and deploy it in Netlify, it returns error like following.

![image](https://user-images.githubusercontent.com/40452856/69471765-0a9a3300-0dde-11ea-8519-cd2d54abd53f.png)

This is the general settings in Netlify, how to deploy it successfully?

![image](https://user-images.githubusercontent.com/40452856/69471787-4c2ade00-0dde-11ea-83fc-d8c289c0b071.png)

**Comment by avatar-kaleb** [comment]
The exact repo or did you make changes before doing so? 

Two possibilities:
1. New version of a gatsby plugin so the query changed
2. You deleted all of the blog posts so the query is failing? Maybe create a test one and see if that helps?

**Comment by FeynmanZhou** [comment]
@avatar-kaleb Nothing changed. Now I can compile successfully in my local, but it requires Netlify login, how can I remove the Netlify authentication when preview it locally? 
![image](https://user-images.githubusercontent.com/40452856/69898447-bde1c980-1394-11ea-883e-e73f2c27bef3.png)


![image](https://user-images.githubusercontent.com/40452856/69898429-8541f000-1394-11ea-9849-756c8ad44262.png)

**Comment by avatar-kaleb** [comment]
try localhost:8000 for your home page, not the /admin :)

The netlify CMS is how you create new blog posts / add images - it a CMS GUI, not the actual site. I just noticed I am getting the same error as you on my builds, so I'll take a look this weekend.

**Comment by FeynmanZhou** [comment]
@avatar-kaleb Using http://localhost:8000 only returned blank page, hope for your solution for the same error, thank you.

**Comment by avatar-kaleb** [comment]
I pushed my changes for the error above, not sure why you're getting a blank page. Could you give me anymore info?
